async function init(){try{var r=await fetch('/api/me');if(!r.ok){window.location.href='/login.html';return;}loadConfigs();}catch(e){window.location.href='/login.html';}}
function S(m,t){var x=document.getElementById('to');x.textContent=m;x.className='toast '+(t||'success');x.style.display='block';setTimeout(function(){x.style.display='none';},3000);}
document.getElementById('cf').onsubmit=async function(e){e.preventDefault();var f=new URLSearchParams();f.append('name',document.getElementById('cn').value);f.append('remarks',document.getElementById('cr').value);var r=await fetch('/api/configs',{method:'POST',body:f});var d=await r.json();if(d.success){S('Created!');document.getElementById('cn').value='';document.getElementById('cr').value='';loadConfigs();}};
async function loadConfigs(){var r=await fetch('/api/configs');var c=await r.json();var h=document.getElementById('cl');if(!c.length){h.innerHTML='<p style="color:#888;text-align:center;padding:20px;">No configs</p>';return;}h.innerHTML=c.map(function(x){return'<div class="config-item'+(x.enabled?'':' disabled')+'"><div class="config-info"><strong>'+(x.name||'Unnamed')+'</strong><br><code class="uuid-text">'+x.uuid+'</code>'+(x.vless_link?'<br><small style="color:#2ecc71">Ready</small>':'')+'</div><div class="config-actions">'+(x.vless_link?'<button class="btn-sm btn-copy" onclick="cp(\''+x.vless_link.replace(/'/g,"\\'")+'\')">Copy</button>':'')+'<button class="btn-sm btn-toggle" onclick="tg('+x.id+')">'+(x.enabled?'Disable':'Enable')+'</button><button class="btn-sm btn-delete" onclick="dc('+x.id+')">Del</button></div></div>';}).join('');}
async function tg(id){await fetch('/api/configs/'+id+'/toggle',{method:'PATCH'});loadConfigs();}
async function dc(id){if(!confirm('Delete?'))return;await fetch('/api/configs/'+id,{method:'DELETE'});S('Deleted');loadConfigs();}
function cp(l){navigator.clipboard.writeText(l).then(function(){S('Copied!');}).catch(function(){prompt('Copy:',l);});}
async function logout(){await fetch('/api/logout',{method:'POST'});window.location.href='/login.html';}
document.addEventListener('DOMContentLoaded',init);
